version: '2'

services:
  kimai2:
    build:
      dockerfile: Dockerfile
      context: .
    image: agileit/kimai2:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - kimai2db
    # volumes:
    environment:
      APP_ENV: prod
      APP_SECRET: alksdlklakjashjkdkjhawukajhfkj89789a7s
      SQL_PROTOCOL: sqlite
      SQL_DATABASE: root
      SQL_PASSWORD: example
      SQL_HOST: kimai2db
  kimai2db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
